### PR TITLE
move cow files into a folder

### PR DESCRIPTION
**Pull request by vivian-dai**
justification: less scrolling to see readme file

### CODE REVIEW

**Comment by vivian-dai** [comment]
also addressing https://github.com/bkendzior/cowfiles/issues/19

**Comment by strugee** [comment]
Licenses cannot "just" be added. Everyone who contributed non-trivial (i.e. copyrightable) code needs to consent to their work being licensed this way.

**Review by bkendzior — CHANGES_REQUESTED** [review]
Remove the License file for now; it's a good thought but most of this ASCII art has been floating around since the BBS days and tracking down the proper owners of the art isn't a project I'm willing to take on.

Also, I'm happy moving the cowfiles into a folder, please edit the `README` so that it reflects the change.

**Comment by bkendzior** [comment]
Thanks for the commit @vivian-dai !

**Pull request merged**
