### PR TITLE
Fix meow cow's eye

### PR DESCRIPTION
**Pull request by ricksbrown**
This PR addresses the issue shown below.

`cowsay -e @ -f meow moo` should produce this:

```
 _____
< moo >
 -----
  \
   \ ,   _ ___.--'''`--''//-,-_--_.
      \`"' ` || \\ \ \\/ / // / ,-\\`,_
     /'`  \ \ || Y  | \|/ / // / - |__ `-,
    /@"\  ` \ `\ |  | ||/ // | \/  \  `-._`-,_.,
   /  _.-. `.-\,___/\ _/|_/_\_\/|_/ |     `-._._)
   `-'``/  /  |  // \__/\__  /  \__/ \
        `-'  /-\/  | -|   \__ \   |-' |
          __/\ / _/ \/ __,-'   ) ,' _|'
         (((__/(((_.' ((___..-'((__,'
```

but actually produces:

```
 _____
< moo >
 -----
  \
   \ ,   _ ___.--'''`--''//-,-_--_.
      \`"' ` || \\ \ \\/ / // / ,-\\`,_
     /'`  \ \ || Y  | \|/ / // / - |__ `-,
    /$eye"\  ` \ `\ |  | ||/ // | \/  \  `-._`-,_.,
   /  _.-. `.-\,___/\ _/|_/_\_\/|_/ |     `-._._)
   `-'``/  /  |  // \__/\__  /  \__/ \
        `-'  /-\/  | -|   \__ \   |-' |
          __/\ / _/ \/ __,-'   ) ,' _|'
         (((__/(((_.' ((___..-'((__,'
```

### CODE REVIEW

**Comment by ricksbrown** [comment]
So this is growing, pretty sure mech-and-cow should look like this:

```
 _____
< Moo >
 -----
      \                            |     |
       \                        ,--|     |-.
                         __,----|  |     | |
                       ,;::     |  `_____' |
                       `._______|    i^i   |
                                `----| |---'| .
                           ,-------._| |== ||//
                           |       |_|P`.  /'/
                           `-------' 'Y Y/'/'
                                     .==\ /_\
   ^__^                             /   /'|  `i
   (oo)\_______                   /'   /  |   |
   (__)\       )\/\             /'    /   |   `i
       ||----w |           ___,;`----'.___L_,-'`\__
       ||     ||          i_____;----\.____i""\____\

```

But currently looks like this (note the missing cow tail, neck and misalignment of mech feet as well as loss of detail on mech feet):

```
 _____
< Moo >
 -----
      \                            |     |
       \                        ,--|     |-.
                         __,----|  |     | |
                       ,;::     |  `_____' |
                       `._______|    i^i   |
                                `----| |---'| .
                           ,-------._| |== ||//
                           |       |_|P`.  /'/
                           `-------' 'Y Y/'/'
                                     .== /_
   ^__^                             /   /'|  `i
   (oo)_______                   /'   /  |   |
   (__)       )/             /'    /   |   `i
       ||----w |           ___,;`----'.___L_,-'`__
       ||     ||          i_____;----.____i""____
```

**Comment by ricksbrown** [comment]
Last one for realsies...

Hypno is missing a little detail, methinks it should like this:

```
 _____
< Moo >
 -----
  \
     ___        _--_
    /    -    /     \
   ( oo   \  (    oo )
   |  oo _;\-/|  oo _|
    \___/######\___/\
      /##############\
     /  ######   ##  #|
    /  ##@##@##       |
   /    ######     ##  \
 <______-------___\  . //_
    |       ____  | | //# \__~__
     \            \  //###  \   \
      |             /\'  ##  ##  ##\   __--~--_
       \_________- /\ )    ^     ##|--########\
  /--~-_\________/_  |          #@##|#######Y##|
 | \ `  /|       /O/ ( ###  \')    ##/######/###/
 \  \  | |       --  |  ###        /LLLLL--###/
  \_ \/  |            \_   \    ) /####_____--
 ___ /    \           /     |   _-####\
(___/     -\_________/     / -- |#####@@@@@@\'_
 (__\_      __,) (.___     ,/    /#####      `@@
      | -\\-          //-//      @@  @@@@@.
      | | \\_       _// //      @\'       \'@@.
      (.)   \_)    / / //                   @@@
                  (_) (_\'

```

But currently looks like this:

```
 _____
< Moo >
 -----
  \
     ___        _--_
    /    -    /     \
   ( oo   \  (    oo )
   |  oo _;\-/|  oo _|
    \___/######\___/\
      /##############\
     /  ######   ##  #|
    /  ##@##@##       |
   /    ######     ##  \
 <______-------___\  . //_
    |       ____  | | //# \__~__
     \            \  //###  \   \
      |             /'  ##  ##  ##\   __--~--_
       \_________- /\ )    ^     ##|--########\
  /--~-_\________/_  |          #@##|#######Y##|
 | \ `  /|       /O/ ( ###  ')    ##/######/###/
 \  \  | |       --  |  ###        /LLLLL--###/
  \_ \/  |            \_   \    ) /####_____--
 ___ /    \           /     |   _-####\
(___/     -\_________/     / -- |#####@@@@@@'_
 (__\_      __,) (.___     ,/    /#####      `@@
      | -\\-          //-//      @@  @@@@@.
      | | \\_       _// //      @'       '@@.
      (.)   \_)    / / //                   @@@
                  (_) (_'
```

**Comment by ricksbrown** [comment]
Ok last issue, I mean it now, had to remove `use utf8;` from psychiatrichelp2.cow because it made cowsay unhappy, check it out.

Before:

```
 _____
< Moo >
 -----
 \      .------------------------.
  \     |       PSYCHIATRIC      |
   \    |         HELP  5?       |
    \   |________________________|
     \  ||     .-"""--.         ||
      \ ||    /        \.-.     ||
        ||   |     ._,     \    ||
        ||   \_/`-'   '-.,_/    ||
        ||   (_   (' _)') \     ||
        ||   /|           |\    ||
        ||  | \     __   / |    ||
        ||   \_).,_____,/}/     ||
      __||____;_--'___'/ (      ||
     |\ ||   (__,\\    \_/------||
     ||\||______________________||
     ||||                        |
     ||||       THE DOCTOR       |
     \|||         IS [IN]   _____|
      \||                  (______)
 jgs   `|___________________//||\\
                           //=||=\\
                           `  ``  `
```

After:

```
 _____
< Moo >
 -----
 \      .------------------------.
  \     |       PSYCHIATRIC      |
   \    |         HELP  5¢       |
    \   |________________________|
     \  ||     .-"""--.         ||
      \ ||    /        \.-.     ||
        ||   |     ._,     \    ||
        ||   \_/`-'   '-.,_/    ||
        ||   (_   (' _)') \     ||
        ||   /|           |\    ||
        ||  | \     __   / |    ||
        ||   \_).,_____,/}/     ||
      __||____;_--'___'/ (      ||
     |\ ||   (__,\\    \_/------||
     ||\||______________________||
     ||||                        |
     ||||       THE DOCTOR       |
     \|||         IS [IN]   _____|
      \||                  (______)
 jgs   `|___________________//||\\
                           //=||=\\
                           `  ``  `
```

**Comment by bkendzior** [comment]
Thanks for the fixes @ricksbrown !

**Pull request merged**
